[tool.kedro]
context_path = "{{ cookiecutter.python_package }}.run.ProjectContext"
package_name = "{{ cookiecutter.python_package }}"
project_name = "{{ cookiecutter.project_name }}"
project_version = "{{ cookiecutter.kedro_version }}"
